### ISSUE TITLE
Please add option to adjust strata

### ISSUE THREAD

**Issue by aeger** [chalkos/RepairMe#26]
I would like to be able to set the strata so UI elements will be on top of the RepairMe bar when opened.

**Comment by chalkos** [comment]
repairme's ui elements were supposed to always be at the bottom of everything. which addon(s) appear below it?

**Comment by pigsflew** [comment]
I'm unsure but it's possible @aeger is talking about in-game UI windows and such? I know it's technically possible to render in lower strata (i've seen it done), but I'm not sure how.

**Comment by chalkos** [comment]
the way nameplatedebuffs does it, it is possible, but I believe that it is only possible if you're drawing game UI, not ImGui.

**Comment by aeger** [comment]
Sorry for the delay, the in-game window is exactly what I meant.  I moved this off in the corner under my mini map to mitigate readability of other windows that are more to the middle of my screen. I had this same issue with Delvui on top of tooltips in the action bar that was less than desirable for me. Don't trouble yourself if making a change like this is a big lift. I'm fine with it in the corner.

**Comment by chalkos** [comment]
I looked into this and Delvui does have an experimental/unstable feature (that they even warn that can cause random crashes) that is quite inneficient but is currently the only way we have that works. From what I gather it works like:
- before drawing Delvui/RepairMe elements, look at all the windows/tooltips/menus/etc that are visible
- change the drawing area to be everything except the areas that have UI elements
- draw Delvui/RepairMe elements (which will not draw over the UI because those are no longer drawable areas)

This would heavily impact your frames (plugins usually don't make them noticeable slower, but this likely would), and so not worth pursuing for now. maybe in the future we will have better/faster ways of doing this
