### ISSUE TITLE
Multiple settings profiles

### ISSUE THREAD

**Issue by Naixatloz** [chalkos/RepairMe#7]
Would it be possible to have different settings depending on your active character ID? For my characters who can repair their own gear, I'd like to receive condition alerts at 99%, but a different threshold for my characters who need to rely on mender NPCs.

**Comment by chalkos** [comment]
This seems like it could be done by adding config profiles and linking profiles to specific characters. if you want different settings, you'd just create a new profile, change it to your liking and link it to the character.

**Comment by chalkos** [comment]
Adding different profiles was overkill, as what we want to behave differently is only the thresholds: high for characters that can repair, and lower for characters that require a visit to the mender.

This means that the minimal solution to this would be to have a secondary set of thresholds that we could use on specific characters. I don't see the need for more than 2 sets of thresholds.

So I added this and I'm currently testing it myself to see if anything crashes in the next day or so because of this, and if everything seems fine I'll deploy it in testing.

It looks like this
![image](https://user-images.githubusercontent.com/98429/175219464-e31c4ff7-acd4-4e09-8a23-6cf384c94747.png)
